---
- name: Install Nginx and create index.html
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create index.html
      copy:
        content: "<h1>Hello from Ansible!</h1>"
        dest: /var/www/html/index.html

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
